### ISSUE TITLE
How to resume my training?

### ISSUE THREAD

**Issue by GravitySaika** [kakaobrain/cxr-clip#4]
I always encounter the situation shown in the following picture during training, where the process is terminated by signal 9. I don't know why this situation always occurs, but now I hope to continue training on the checkpoint that I have trained for 4 epochs. How should I do this?

```
12172/13725 [4:44:35<35:03,  1.35s/it, lr=['0.00004109'], loss=0.975784, CUDA-Mem=0%, CUDAUtil=0%]WARNING:torch.distributed.elastic.rendezvous.dynamic_rendezvous:The node 'a4000x4313_1543408_0' has failed to send a keep-alive heartbeat to the rendezvous '78d6761b-372b-4b1a-afe6-abb8735493a4' due to an error of type RendezvousTimeoutError.                                                                                              
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1543460 closing signal SIGTERM                                            
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 1543461) of binary: /home/gem/anaconda3/envs/cxr-clip/bin/python                                                                                                                                  
Traceback (most recent call last):                                                                                                              
  File "/home/gem/anaconda3/envs/cxr-clip/bin/torchrun", line 8, in <module>                                                                    
    sys.exit(main())                                                                                                                            
  File "/home/gem/anaconda3/envs/cxr-clip/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, i
n wrapper                                                                                                                                       
    return f(*args, **kwargs)                                                                                                                   
  File "/home/gem/anaconda3/envs/cxr-clip/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main                              
    run(args)                                                                                                                                   
  File "/home/gem/anaconda3/envs/cxr-clip/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run                               
    elastic_launch(                                                                                                                             
  File "/home/gem/anaconda3/envs/cxr-clip/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__                 
    return launch_agent(self._config, self._entrypoint, list(args))                                                                             
  File "/home/gem/anaconda3/envs/cxr-clip/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent             
    raise ChildFailedError(                                                                                                                     
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:                                                                              
========================================================                                                                                        
train.py FAILED                                                                                                                                 
--------------------------------------------------------                                                                                        
Failures:                                                                                                                                       
  <NO_OTHER_FAILURES>                                                                                                                           
--------------------------------------------------------                                                                                        
Root Cause (first observed failure):                                                                                                            
[0]:                                                                                                                                            
  time      : 2024-04-09_16:19:50                                                                                                               
  host      : a4000x4313                                                                                                                        
  rank      : 1 (local_rank: 1)                                                                                                                 
  exitcode  : -9 (pid: 1543461)                                                                                                                 
  error_file: <N/A>                                                                                                                             
  traceback : Signal 9 (SIGKILL) received by PID 1543461                                                                                        
========================================================
```

**Comment by GravitySaika** [comment]
I found that the program was terminated because it would cause a large amount of memory usage. I don't know how to handle this issue?
```
[799503.967722] Out of memory: Killed process 1543461 (python) total-vm:84433476kB, anon-rss:14657368kB, file-rss:70760kB, shmem-rss:1938768kB, UID:1000 pgtables:112868kB oom_score_adj:0
```

**Comment by kihyunU** [comment]
This repository does not support the resume. 
Also, regarding memory issues, we have confirmed that [adding .item() during logging](https://github.com/kakaobrain/cxr-clip/commit/6a4802c5b11d02d7a6e80819756fe70303829c98) helps alleviate the issue. Thank you for reporting. If the issue persists, reducing the batch size might also be a solution.
